services:
  jekyll:
    image: jekyll/jekyll
    command: jekyll serve --host 0.0.0.0 --livereload --drafts --force_polling
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll